header = """/*
 * Copyright 2020 Mozilla Foundation. See the COPYRIGHT
 * file at the top-level directory of this distribution.
 *
 * Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
 * https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
 * <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
 * option. This file may not be copied, modified, or distributed
 * except according to those terms.
**/
"""

braces = "SameLine"
include_guard = "uax14_rs_h"
include_version = false
language = "C"
line_length = 100
namespaces = []
no_includes = true
sys_includes = ["stdint.h"]
tab_width = 2

[export]
include = []
exclude = ["pango_language_from_string", "pango_get_log_attrs", "CFStringCreateWithCharactersNoCopy", "CFStringTokenizerAdvanceToNextToken", "CFStringTokenizerCreate", "CFStringTokenizerGetCurrentTokenRange"]
item_types = ["functions"]
