name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: wget https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/LineBreakTest.txt -O tools/LineBreakTest.txt && cargo test --verbose
