name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
        - x86_64-apple-darwin
        - x86_64-unknown-linux-gnu
        - x86_64-pc-windows-msvc
        include:
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-pc-windows-msvc
          os: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libpango1.0-dev
    - name: Setup Rust
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --target ${{ matrix.target }} --verbose
    - name: Run tests (with platfom_fallback)
      run: |
        curl https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/LineBreakTest.txt -o tools/LineBreakTest.txt
        cargo test --verbose --features platform_fallback
