name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libpango1.0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests (with platfom_fallback)
      run: |
        curl https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/LineBreakTest.txt -o tools/LineBreakTest.txt
        cargo test --verbose --features platform_fallback
